### ISSUE TITLE
Update modulejs version

### ISSUE THREAD

**Issue by Frexuz** [ales-vilchytski/modulejs-rails#1]
2.2.0 is out :)

**Comment by ales-vilchytski** [comment]
Right, Rails 5 too :)
I will check it out, but there were issues with even 2.0 version - some breaking changes were made there.

**Comment by ales-vilchytski** [comment]
I've just pushed new version to rubygems. Seems working.
Please check it
`gem 'modulejs-rails', '2.2.0'`

Please let me know if it's working - I'll close issue then

**Comment by Frexuz** [comment]
Works great, thanks! :)
